# All the below fields are required for successful operator registration.

# To learn more about operator fields
# https://github.com/Layr-Labs/eigenlayer-contracts/blob/92ccacc868785350973afc15e90a18dcd39fbc0b/src/contracts/interfaces/IDelegationManager.sol#L21:
operator:
  address: 0x301EBd04b194FF7dC8064CF229D9e0B3537f4CF7
  earnings_receiver_address: 0x301EBd04b194FF7dC8064CF229D9e0B3537f4CF7
  delegation_approver_address:  0x0000000000000000000000000000000000000000
  staker_opt_out_window_blocks: 0
  metadata_url: https://raw.githubusercontent.com/wesfloyd/test-da-operator/main/metadata.json


# EigenLayer Slasher contract address
# This will be provided by EigenLayer team
el_slasher_address: 0xD11d60b669Ecf7bE10329726043B3ac07B380C22

# Address of BLS Public Key Compendium contract
# This will be provided by EigenLayer team
bls_public_key_compendium_address: 0xc81d3963087Fe09316cd1E032457989C7aC91b19

# ETH RPC URL to the ethereum node you are using for on-chain operations
eth_rpc_url: https://rpc.ankr.com/eth_goerli

# Signer Type to use
# Supported values: local_keystore
signer_type: local_keystore

# Full path to local ecdsa private key store file
private_key_store_path: /home/wes/.eigenlayer/operator_keys/ecdsa-test-key-1.ecdsa.key.json

# Full path to local bls private key store file
bls_private_key_store_path: /home/wes/.eigenlayer/operator_keys/bls-test-key-1.bls.key.json

# Chain ID: 1 for mainnet, 5 for Goerli, 31337 for local
chain_id: 5
